import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "@/styles/globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Suspense } from "react";
import QueryProvider from "@/providers/QueryProvider";
import AuthSession from "@/providers/AuthSessionProvider";
import UserProfileServerProvider from "@/providers/UserProfileServerProvider";
import Loading from "@/components/Loading";

export const metadata: Metadata = {
  title: "Smart Book App",
  description: "Generated by create next app",
};

const sans = Nunito({
  subsets: ["latin"],
  variable: "--font-sans",
});

type LayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Readonly<LayoutProps>) {
  return (
    <html lang="en">
      <body className={`${sans.variable} ${sans.className} antialiased`}>
        <AuthSession>
          <Suspense fallback={<Loading />}>
            <UserProfileServerProvider>
              <QueryProvider>{children}</QueryProvider>
            </UserProfileServerProvider>
          </Suspense>
        </AuthSession>
        <Toaster
          position="top-right"
          closeButton
          duration={3000}
          richColors
          swipeDirections={["left", "right"]}
        />
      </body>
    </html>
  );
}
